### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Falcone8** [Alternative-Profit/Amazon-Bot#2]
`File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/Users/Desktop/Amazon-Bot/main.py", line 31, in start
    product = Product(get_asin(url))
  File "/Users/Desktop/Amazon-Bot/utils/tools.py", line 6, in get_asin
    return re.findall(r'/(?:dp|o|gp|-)\/(B[0-9]{2}[0-9A-Z]{7}|[0-9]{9}(?:X|[0-9]))/', text)[0]
IndexError: list index out of range`

How can I fix

**Comment by Falcone8** [comment]
@Falcone8 I fix in this moment

**Comment by Falcone8** [comment]
Fixed Thank you so much

**Comment by GitUltroid** [comment]
Lai mandato nel di Telethon o pure no?

**Comment by GitUltroid** [comment]
@Falcone8 A ok
